### ISSUE TITLE
Bump version to 0.7.0?

### ISSUE THREAD

**Issue by dwbrite** [Yatekii/imgui-wgpu-rs#14]
It looks like some dependencies were recently version bumped in this repo, but the version `imgui-wgpu` itself was not bumped. Is it ready to be published as 0.7.0, or is more work needed?

**Comment by Yatekii** [comment]
I am not sure if a minor version is warranted just for dep bumping? Do you need it for any reason?

**Comment by dwbrite** [comment]
Perhaps it could be a patch (0.6.1), but I think changing dependency versions counts as a breaking change. I could be wrong, but I believe if someone is using `imgui-wgpu = "^0.6"` and `imgui = "^0.3"`, releasing this version bump as `0.6.1` would break their project, but releasing `0.7.0` would not.

Either way I'm gunning for a new release on crates.io so that I can send a PR to [imgui-glfw-support](https://crates.io/crates/imgui-glfw-support), and get _that_ published with support for wgpu 0.5 and imgui 0.4.

I hope I'm not coming off as entitled, I'm just trying to push the state of `wgpu` on crates.io :)

**Comment by m4b** [comment]
Is a new release happening here? 0.4 imgui would be nice (and agree, this should be a 0.7 release)

**Comment by Yatekii** [comment]
Released =)
