### ISSUE TITLE
Delete texture uploaded using `upload_texture`?

### ISSUE THREAD

**Issue by WeAthFoLD** [Yatekii/imgui-wgpu-rs#23]
Currently there is an exposed API, `Renderer::upload_texture`, which can be used to render custom textures .However, there is no corresponding `Renderer::remove_texture(&mut self, TextureId)` function to remove textures when they aren't used.

Another unrelated question: Can we have an API to directly add an `wgpu::Texture` to obtain `TextureId`? Current API makes many parameters of texture fixed, such as texture format and mipmap level.

**Comment by Yatekii** [comment]
Fixed in #20.
