### ISSUE TITLE
create texture for use with imgui::Image

### ISSUE THREAD

**Issue by luke-titley** [Yatekii/imgui-wgpu-rs#24]
Hey,
I'm rendering to a wgpu texture and I would like to be able to display it with imgui::Image. There's no obvious way for me to create this texture using imgui-wgpu-rs. If there is a way, can you please tell me? Otherwise, would you accept a pull request which adds this?

Thanks,
Luke

**Comment by Yatekii** [comment]
I am not sure how one would do this :/ We have support for custom textures in imgui-wgpu, but I think for diplaying it in an Image might need additional bits. I'll happily accept a PR :)

**Comment by luke-titley** [comment]
You're already using imgui::Image in custom textures. The only difference is, I don't want to upload data. I want to render to the texture using wgpu. It's for making a viewport. I need both the imgui::TextureId and also the wgpu::Texture. The TextureId for imgui::Image and the wgpu::Texture, so that I can render to it directly.

**Comment by luke-titley** [comment]
Maybe I'll just tinker with the Renderer::upload_texture and Texture struct, and see what I can come up with ... unless I'm being really stupid and there's another way.

**Comment by Yatekii** [comment]
Fixed #25.
