### ISSUE TITLE
Hello World example build fails

### ISSUE THREAD

**Issue by felixfaire** [Yatekii/imgui-wgpu-rs#45]
Hi, this looks really useful but the example build seems to fail out of the box.

```
error[E0308]: mismatched types
  --> examples/hello_world.rs:66:9
   |
66 |         &window,
   |         ^^^^^^^ expected struct `winit::window::Window`, found a different struct `winit::window::Window`
   |
   = note: expected reference `&winit::window::Window` (struct `winit::window::Window`)
              found reference `&winit::window::Window` (struct `winit::window::Window`)
   = note: perhaps two different versions of crate `winit` are being used?
```

It seems like quite a strange error as the types clearly match. I'm quite new to rust so the error may be on my part but any help would be appreciated. Thanks

Macos
rustc 1.49.0

**Comment by felixfaire** [comment]
using winit 0.23 everywhere is the cargo.toml seems to fix this but i'm not sure which of the crates is creating the conflict without doing this.

**Comment by cwfitzgerald** [comment]
Is this on master?

**Comment by felixfaire** [comment]
yes it is on master.

I'm also noticing a lot of mouse event input lag on macos but that might be worth a separate issue (and [could be a a winit problem](https://github.com/rust-windowing/winit/issues/1737))

**Comment by cwfitzgerald** [comment]
This repros with something else. Will investigate tonight. Will likely just need to release 0.14 with a fixed deps.
