### ISSUE TITLE
Update to wgpu-rs 0.8

### ISSUE THREAD

**Issue by klashenriksson** [Yatekii/imgui-wgpu-rs#54]
Hello!

wgpu-rs 0.8 was just released and had some minor changes to structure names and parameters. I have a fork ready which is updated to use wgpu 0.8, should I do a PR of that to bring this up to 0.8? :)

**Comment by klashenriksson** [comment]
update: I spoke too soon, there's some runtime issues causing a crash that I believe is related to the shaders..

**Comment by Uriopass** [comment]
Any update? Did you manage to get it working? I might take a look if you didn't :-)

**Comment by benmkw** [comment]
@Uriopass maybe you can look at https://github.com/Yatekii/imgui-wgpu-rs/pull/52#issuecomment-832811358 which still at least has the 4 byte issue

**Comment by klashenriksson** [comment]
Hi! I did get it working, however the fix is certainly not the most effective one, but works fine for my cases atm. Upon index upload I just convert the indices to u32's instead of u16's. 

Have a look at https://github.com/klashenriksson/imgui-wgpu-rs/commits/wgpu-v0.8 (and https://github.com/klashenriksson/imgui-wgpu-rs/commit/3c01713adac29c3c7b0414a00f6985118128d58f for the alignment fix). I dont really have the bandwidth to do a proper fix for this atm but maybe my code can help get you started :)

**Comment by Uriopass** [comment]
Found the issue upstream, buffer initialization was not done properly when providing unaligned data :-)

**Comment by klashenriksson** [comment]
Nice! Good find :)

**Comment by benmkw** [comment]
@Uriopass nice, it still seems to be an issue that TriangleList can not be used with u16 indices though?

I get `[0.094421 ERROR]()(no module): Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }` when using u32 as the index format (which is wrong as far as I can see) although rendering works, I'm not sure why though 😄 when I change it to u16 I  get `strip index format was not set to None but to Some(Uint16) while using the non-strip topology TriangleList`

**Comment by Uriopass** [comment]
> when I change it to u16 I get strip index format was not set to None but to Some(Uint16) while using the non-strip topology TriangleList

I'm pretty sure imgui uses a TriangleList topology :) you should keep the 
PrimitiveTopology::TriangleList
and keep strip_index_format to None.

I do get the error "[0.094421 ERROR]()(no module): Unexpected varying type: Array { base: [1], size: Constant([5]), stride: 4 }" however I think that might just be a naga problem and it works for me it's not critical.

**Comment by benmkw** [comment]
> you should keep the PrimitiveTopology::TriangleList

yes thats what I figured as well but when you look at `upload_index_buffer` and `DrawIdx` you can see that its u16 so it may only work by luck ...

> keep strip_index_format to None

this makes the indices be u32

**Comment by benmkw** [comment]
ah right somehow mixed None and Default in my mind and did not know enough about the API, thanks for the explanation 👍
