### ISSUE TITLE
Support winit 0.25

### ISSUE THREAD

**Issue by andraantariksa** [Yatekii/imgui-wgpu-rs#64]
The title say everything

**Comment by cwfitzgerald** [comment]
There does not seem to be a winit release greater than 0.25, is there something you are needing support for in particular?

**Comment by ChristianIvicevic** [comment]
Now there is and while attempting to attach my window instance to the platform I am receiving a version/type mismatch:

![Screenshot 2021-09-02 at 02 11 23](https://user-images.githubusercontent.com/45569997/131761571-3bfe0e0e-e0b3-47ac-a062-29be53f4cf63.png)

**Comment by andraantariksa** [comment]
> There does not seem to be a winit release greater than 0.25, is there something you are needing support for in particular?

I mean winit 0.25. Maybe I should change the title.

I need some of the features in winit 0.25.

**Comment by cwfitzgerald** [comment]
Oh I see. I didn't realize we didn't support 0.25 formally. It should be as easy as bumping the cargo.toml. We don't use that many winit features. You're using the simple api?

**Comment by andraantariksa** [comment]
Simple api?

**Comment by cwfitzgerald** [comment]
See https://github.com/Yatekii/imgui-wgpu-rs/blob/master/examples/basic_simple_api.rs

If you aren't using the simple api, winit isn't even a dependency of ours.

**Comment by andraantariksa** [comment]
Nope, I need access to winit

**Comment by cwfitzgerald** [comment]
My point is that if you aren't using the simple api, we don't have a winit dependency at all. What api are you calling that is getting this mismatch?

**Comment by andraantariksa** [comment]
I see, my bad. Just need to change the default features.

```
imgui-winit-support = { version = "0.7.0", default-features = false, features = ["winit-25"] }
```

Closing this issue.
