### ISSUE TITLE
Crashing with `Invalid ScissorRect Parameters`

### ISSUE THREAD

**Issue by aleokdev** [Yatekii/imgui-wgpu-rs#77]
## Description

Trying to use this crate on my project I get an `Invalid ScissorRect Parameters` error from WGPU by trying to draw the demo window. This also happens when I try to run the hello-world example.

## Repro steps

1. Clone this repository
2. `cargo run --example hello-world` 

## Extra Materials

Here's the output from the example:
```
MESA-INTEL: warning: Haswell Vulkan support is incomplete
[2021-10-14T09:55:52Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Vulkan)>`
    In a set_scissor_rect command
    Invalid ScissorRect parameters

', /home/aleok/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.11.0/src/backend/direct.rs:2195:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## System Information

`imgui-wgpu-rs` version: Tested with both current master branch head & 0.18.0
OS info:
```
OS: Manjaro Linux x86_64 
Kernel: 5.10.70-1-MANJARO 
Resolution: 1366x768 
DE: Plasma 5.22.5 
WM: KWin 
CPU: Intel i5-4210U (4) @ 2.700GHz 
GPU: Intel Haswell-ULT 
GPU: AMD ATI Radeon HD 8670A/8670M/8690M / R5 M330 / M430 / Radeon 520 Mobile 
Memory: 1323MiB / 7876MiB
```

**Comment by griffi-gh** [comment]
I have the same issue

**Comment by cwfitzgerald** [comment]
Would it be possible to print out the values that aren't working correctly? I wonder if this is a wgpu issue or an issue here.

**Comment by Lowentwickler** [comment]
This may happen when you inner size of the window does not match `wgpu` surface. One of the solutions, that we used in [this dotrix PR !157](https://github.com/lowenware/dotrix/pull/157/files#r830522908) for egui, is to use surface size instead of `winit` window inner size to calculate scissors rect.

**Comment by petersn** [comment]
I am getting this issue also, with `imgui-wgpu` 0.20.0, as freshly cloned -- the same issue where I just run the hello example and get a crash. The output I see:

```
$ RUST_BACKTRACE=1 cargo run --example hello-world
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/hello-world`
[2022-08-29T00:57:11Z ERROR wgpu::backend::direct] Handling wgpu errors as fatal by default
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In a RenderPass
      note: encoder = `<CommandBuffer-(0, 1, Vulkan)>`
    In a set_scissor_rect command
    Scissor Rect { x: 0, y: 0, w: 1277, h: 2121 } is not contained in the render target Extent3d { width: 1276, height: 2121, depth_or_array_layers: 1 }

', /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2391:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/panicking.rs:142:14
   2: wgpu::backend::direct::default_error_handler
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2391:5
   3: core::ops::function::Fn::call
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/ops/function.rs:77:5
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/alloc/src/boxed.rs:1949:9
   5: wgpu::backend::direct::ErrorSinkRaw::handle_error
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2377:17
   6: wgpu::backend::direct::Context::handle_error
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:261:9
   7: <wgpu::backend::direct::Context as wgpu::Context>::command_encoder_end_render_pass
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/backend/direct.rs:2087:13
   8: <wgpu::RenderPass as core::ops::drop::Drop>::drop
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.13.1/src/lib.rs:3143:13
   9: core::ptr::drop_in_place<wgpu::RenderPass>
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/ptr/mod.rs:487:1
  10: core::mem::drop
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/mem/mod.rs:988:24
  11: hello_world::main::{{closure}}
             at ./examples/hello-world.rs:222:17
  12: winit::platform_impl::platform::sticky_exit_callback
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:753:5
  13: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/mod.rs:320:17
  14: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/x11/mod.rs:392:9
  15: winit::platform_impl::platform::EventLoop<T>::run
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/platform_impl/linux/mod.rs:669:56
  16: winit::event_loop::EventLoop<T>::run
             at /home/snp/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.26.1/src/event_loop.rs:154:9
  17: hello_world::main
             at ./examples/hello-world.rs:107:5
  18: core::ops::function::FnOnce::call_once
             at /rustc/878aef79dcdf59d19bb8482202dc55e58ceb62ff/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The rect (`Rect { x: 0, y: 0, w: 1277, h: 2121 }` in the example) seems to always be exactly one wider than the render target Extent3d, regardless of what size monitor I launch it on. In case it's relevant, I'm running i3.

**Comment by petersn** [comment]
Okay, very interesting! I hope this is helpful: When I use i3 in Ubuntu 22.04 it crashes in the above way (the Rect always being one too wide for the render target), but with Ubuntu's default gnome desktop manager it runs flawlessly. I hope this is helpful.

**Comment by petersn** [comment]
Okay, one more hint: It *does* work under i3, if it's filling specific-sized vacancies in the UI. Like, on my 4k monitor if I have one pane already present then the demo works (taking half the screen, minus borders), but with 2, 3, or 4 panes vertically splitting the screen launching the example crashes, but then at 5 panes vertically splitting the screen (so that the demo app becomes the sixth pane, to be clear) it works again.

Perhaps there's some annoying numerical issue with off-by-ones or something with certain specific sizes of Rects, then?

**Comment by Lymia** [comment]
This happens to me only when I resize the window.

**Comment by ngortheone** [comment]
On FreeBSD-14 this causes kernel crash - most likely this bug triggers another bug inside of the kernel (freebsd uses drm drivers ported from Linux)

I can confirm what @Lymia says. This is DPI related. I use sway (wayland) and when global desktop DPI scale set to 2 the crash happens. When I set DPI scale to 1 - everything works fine.

**Comment by Yatekii** [comment]
Hey @ngortheone :P How's it going? :) (sorry for offtopic an you might not remember me ;))

**Comment by ngortheone** [comment]
Hey @Yatekii , doing great! How about yourself?  Your nick/avatar seems very familiar, where did we interact before?

**Comment by Yatekii** [comment]
We worked at the same company ;) Everything great over here too :)
