### ISSUE TITLE
Widgets disappears when the containing window is moved

### ISSUE THREAD

**Issue by jomag** [Yatekii/imgui-wgpu-rs#81]
## Description

I'm evaluating imgui-rs and different renderers, and when running the builtin demo in imgui-wgpu-rs I found that the widgets strangely disappears when I move the window:

![imgui-wgpu](https://user-images.githubusercontent.com/430635/148296121-53617dc3-24d9-4f66-91a7-9511fe6a3951.gif)

## Repro steps

With commit 61ad787042999231a12560622d65ddb08e81e75e:

`cargo run --example hello-world`

## System Information

MacBook Pro M1, MacOS Monterey 12.0.1

**Comment by druks-232cc** [comment]
This seems to happen when the winit window is resized and the widget is moved out of the original window size.

With a bit of debugging, I found out that in `Renderer::prepare(...)`, `render_data.fb_size` is never updated upon resize, although it's still passed as an argument to `Renderer::render_draw_list(...)`

This small patch fixes the issue for me:
```
--- imgui-wgpu-rs-0.19.0/src/lib.rs.orig	2022-01-15 22:56:48.479961204 +0100
+++ imgui-wgpu-rs-0.19.0/src/lib.rs	2022-01-15 22:57:23.079960825 +0100
@@ -514,6 +514,7 @@
             || (render_data.last_pos[0] - draw_data.display_pos[0]).abs() > std::f32::EPSILON
             || (render_data.last_pos[1] - draw_data.display_pos[1]).abs() > std::f32::EPSILON
         {
+            render_data.fb_size = [fb_width, fb_height];
             render_data.last_size = draw_data.display_size;
             render_data.last_pos = draw_data.display_pos;
 
```
