### ISSUE TITLE
Outdated imgui and wgpu versions

### ISSUE THREAD

**Issue by Calcoph** [Yatekii/imgui-wgpu-rs#88]
imgui 0.9 released recently and there's also wgpu 1.14

It would be nice to add support for these new versions.

**Comment by parasyte** [comment]
#87 is currently awaiting feedback from a maintainer.

**Comment by cwfitzgerald** [comment]
Hai, I am that maintainer, sorry for the delay, will look at merging #87.

**Comment by cwfitzgerald** [comment]
Will do a release tomorrow, if I forget yell at me

**Comment by parasyte** [comment]
Ping @cwfitzgerald. Are you planning the release? (We're not necessarily blocked, just asking since you requested a reminder.)

**Comment by cwfitzgerald** [comment]
Thank you!

0.21.0 is out! https://github.com/Yatekii/imgui-wgpu-rs/releases/tag/v0.21.0
