### ISSUE TITLE
Docking not Working ?

### ISSUE THREAD

**Issue by Snowiiii** [Yatekii/imgui-wgpu-rs#93]
## Description

Docking was Implementet in imgui-rs [0.9.0](https://github.com/imgui-rs/imgui-rs/releases/tag/v0.9.0) since then it can be Enabled using the 'docking' feature, But it dosn't work i guess this is a WGPU Problem

## System Information
Linux Arch.
```
imgui = { version = "0.10", features = [ "docking" ] }
imgui-winit-support = { version = "0.10"  }
imgui-wgpu = "0.22.0"

winit = "0.27.1"
wgpu = "0.15.1"
```

**Comment by PixelboysTM** [comment]
I dont know if this is obvious but for docking to work you need to set the DOCKING_ENABLE feature flag when after creating the context.
